apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: bluegreen
spec:
  selector:
    app: myapp
    version: blue   # ou green pour basculer
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
